FROM alpine/git AS vcs
RUN cd / && git clone https://github.com/wakaleo/game-of-life.git

FROM maven:3-amazoncorretto-8 AS build
COPY --from=vcs /game-of-life /game-of-life
RUN cd game-of-life && mvn package

FROM tomcat:9-jdk8
COPY --from=build /game-of-life/gameoflife-web/target/*.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
