---
version: "3.8"
services:
  nop:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_SERVER=nop_db
    ports:
      - "35000:5000"
    depends_on:
      - nop_db
    networks:
      - nop_network
  nop_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=nop
      - MYSQL_PASSWORD=rootroot
      - MYSQL_DATABASE=nop
    networks:
      - nop_network
    volumes:
      - nop-db:/var/lib/mysql
volumes:
  nop-db:
networks:
  nop_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"
